name: calendar_view_pt
description: A Flutter package allows you to easily implement all calendar UI and calendar event functionality.
version: 1.0.0
homepage: https://github.com/teixeirazeus/calendar_view_pt
issue_tracker: https://github.com/teixeirazeus/calendar_view_pt/issues

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
